const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups=['Orientamento','Le fondamenta','Il linguaggio musicale','Comporre e arrangiare','La fisica del suono','Ascolto e produzione','Mettere in pratica'];
const refs={music:['Music Theory for the 21st-Century Classroom','https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'],dsp:['The Scientist and Engineer’s Guide to DSP','https://www.dspguide.com/pdfbook.htm'],euclid:['Toussaint · Euclidean Rhythms','https://cgm.cs.mcgill.ca/~godfried/publications/banff.pdf'],loudness:['ITU-R BS.1770 · Loudness e true peak','https://www.itu.int/rec/R-REC-BS.1770'],synth:['Ableton · Riferimento degli strumenti','https://www.ableton.com/en/live-manual/12/live-instrument-reference/']};
let state={done:[],notes:{},answers:{}},storageOK=true,current=0;
try{let saved=JSON.parse(localStorage.getItem('music-theory-v1'));if(saved&&Array.isArray(saved.done)&&saved.notes&&saved.answers){state=saved;state.done=state.done.filter(id=>CHAPTERS.some(c=>c.id===id));}}catch{storageOK=false;}
function save(){try{localStorage.setItem('music-theory-v1',JSON.stringify(state));}catch{storageOK=false;}if($('.notes-status'))$('.notes-status').textContent=storageOK?'Salvato in questo browser. Esporta gli appunti per conservarne una copia.':'Salvataggio locale non disponibile: esporta gli appunti prima di chiudere.';}
function navigation(){let q=$('#search').value.trim().toLocaleLowerCase('it'),last=-1,count=0;$('#nav').innerHTML=CHAPTERS.map((c,i)=>{if(q&&!((c.title+' '+c.text).toLocaleLowerCase('it').includes(q)))return '';count++;let head=last!==c.group?`<div class="nav-group">${groups[c.group]}</div>`:'';last=c.group;return head+`<a href="#${c.id}" class="${i===current?'active ':''}${state.done.includes(c.id)?'done':''}" ${i===current?'aria-current="page"':''}><span class="num">${state.done.includes(c.id)?'✓':c.id.slice(0,2)}</span><span>${escapeHTML(c.title)}</span></a>`;}).join('')||'<p class="empty">Nessun risultato. Prova un termine più breve.</p>';$('#search-status').textContent=q?count+' capitoli trovati':'';$('#progress-count').textContent=state.done.length+' / '+CHAPTERS.length;$('#progress').value=state.done.length;}
function cover(i){return `<svg viewBox="0 0 850 90" role="img" aria-label="Dalle pulsazioni alle onde: motivo grafico della guida"><defs><linearGradient id="hero-grad"><stop stop-color="#6be0d2"/><stop offset="1" stop-color="#c9afff"/></linearGradient></defs>${Array.from({length:48},(_,n)=>{let h=12+52*Math.abs(Math.sin(n*.23+i*.5))*((n%4+2)/5);return `<rect x="${n*18}" y="${45-h/2}" width="5" height="${h}" rx="2" fill="url(#hero-grad)" opacity="${.4+(n%4)*.18}"/>`;}).join('')}</svg>`;}
function render(){stopAudio();let idx=CHAPTERS.findIndex(c=>c.id===location.hash.slice(1));current=idx<0?0:idx;const c=CHAPTERS[current];document.title=c.title+' · Teoria musicale';$('#page').innerHTML=`<div class="eyebrow">${groups[c.group]} / capitolo ${c.id.slice(0,2)}</div><h1 id="chapter-title" tabindex="-1">${escapeHTML(c.title)}</h1><div class="chapter-meta"><span>${Math.max(2,Math.ceil(c.text.split(/\s+/).length/170))} min di lettura</span><span>Ascolto + esercizio</span><span>EN (IT) · notazione doppia</span></div><a class="jump-lab" href="#lab-root" id="jump-lab">↓ Vai al laboratorio</a><div class="chapter-hero">${cover(current)}</div><article class="article">${c.html}</article><section class="quiz" aria-labelledby="quiz-title"><span class="lab-tag">VERIFICA LA COMPRENSIONE</span><h2 id="quiz-title">${escapeHTML(c.question)}</h2><div class="quiz-options">${c.options.map((o,i)=>`<button data-answer="${i}">${escapeHTML(o)}</button>`).join('')}</div><div class="quiz-result" role="status"></div></section><div class="chapter-end"><button id="complete" class="primary">${state.done.includes(c.id)?'✓ Completato · annulla':'Segna come completato'}</button><div class="chapter-nav"><button id="prev" ${current===0?'disabled':''}>← Precedente</button><button id="next" ${current===CHAPTERS.length-1?'disabled':''}>Successivo →</button></div></div><section class="notes"><label for="notes-text">I tuoi appunti · previsione, ascolto, conclusione</label><textarea id="notes-text" placeholder="Che cosa hai cambiato? Che cosa hai sentito?"></textarea><div class="notes-status" role="status"></div></section>`;
$$('.article table').forEach(table=>{const wrap=document.createElement('div');wrap.className='table-scroll';table.before(wrap);wrap.append(table);});
let key=current===24?'euclid':current===25?'loudness':current>=15?(current===21?'synth':'dsp'):'music';const ref=refs[key];$('.article').insertAdjacentHTML('beforeend',`<p class="source-note">Per approfondire: <a href="${ref[1]}" target="_blank" rel="noopener noreferrer">${ref[0]}</a>. Vedi anche <a href="FONTI.md">fonti e criteri editoriali</a>. Esempi e percorsi didattici originali.</p>`);
$('#jump-lab').onclick=e=>{e.preventDefault();$('#lab-root').scrollIntoView({behavior:'auto',block:'start'});};
$('#notes-text').value=state.notes[c.id]||'';$('#notes-text').oninput=e=>{state.notes[c.id]=e.target.value;save();};save();
function feedback(i){$$('[data-answer]').forEach(b=>{b.classList.remove('correct','wrong');if(+b.dataset.answer===c.answer)b.classList.add('correct');else if(+b.dataset.answer===i)b.classList.add('wrong');});$('.quiz-result').textContent=(i===c.answer?'Corretto. ':'Da rivedere. ')+c.explanation;}
$$('[data-answer]').forEach(b=>b.onclick=()=>{state.answers[c.id]=+b.dataset.answer;feedback(+b.dataset.answer);save();});if(Number.isInteger(state.answers[c.id]))feedback(state.answers[c.id]);
$('#complete').onclick=()=>{state.done=state.done.includes(c.id)?state.done.filter(id=>id!==c.id):[...state.done,c.id];save();$('#complete').textContent=state.done.includes(c.id)?'✓ Completato · annulla':'Segna come completato';navigation();};$('#prev').onclick=()=>location.hash=CHAPTERS[current-1].id;$('#next').onclick=()=>location.hash=CHAPTERS[current+1].id;
mountLab(c.lab,$('#lab-root'));navigation();$('.sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');window.scrollTo(0,0);}
$('#search').oninput=navigation;$('#menu').onclick=()=>{const open=$('.sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open));};$('#stop-all').onclick=()=>stopAudio();document.addEventListener('keydown',e=>{if(e.key==='Escape'){stopAudio();$('.sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');}});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAudio();});
$('#master-volume').oninput=e=>{masterLevel=+e.target.value/100;$('#master-value').textContent=e.target.value+'%';if(masterGain&&audioCtx)masterGain.gain.setTargetAtTime(masterLevel,audioCtx.currentTime,.02);};
$('#print').onclick=()=>{stopAudio();window.print();};$('#export').onclick=()=>{const txt='# I miei appunti · Teoria musicale\n\n'+CHAPTERS.map(c=>`## ${c.title}\n\nStato: ${state.done.includes(c.id)?'completato':'da completare'}\n\n${state.notes[c.id]||'—'}\n`).join('\n');download(new Blob([txt],{type:'text/markdown;charset=utf-8'}),'Appunti-Teoria-Musicale.md');};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
window.addEventListener('hashchange',render);render();
