const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const base=__dirname;
const {marked}=require('C:/Users/tizia/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/marked');
const chapters=JSON.parse(fs.readFileSync(path.join(base,'indice.json'),'utf8'));
for(const c of chapters){const md=fs.readFileSync(path.join(base,'capitoli',c.id+'.md'),'utf8');c.text=md;c.html=marked.parse(md.replace(/^# .*\r?\n/,'').split('## Verifica')[0]).replace(/<!-- LAB:.*?-->/s,'<div id="lab-root"></div>');}
const css=fs.readFileSync(path.join(base,'stile.css'),'utf8');
const js=['laboratori.js','app.js'].map(p=>fs.readFileSync(path.join(base,p),'utf8')).join('\n');new vm.Script(js);
const html=`<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Teoria musicale, sintesi e ascolto: 27 capitoli con laboratori sonori e grafici interattivi, esercizi e appunti."><title>Teoria musicale · Studio Manual 02</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='8' fill='%2348d2d2'/%3E%3Cpath d='M4 16q6-16 12 0t12 0' fill='none' stroke='%23101417' stroke-width='3'/%3E%3C/svg%3E"><style>${css}</style></head><body><a href="#chapter-title" class="skip">Salta al contenuto</a><aside class="sidebar" aria-label="Indice"><div class="brand"><div class="brand-top">∿ &nbsp; STUDIO MANUAL / 02</div><div class="brand-name">Teoria musicale<span>.</span></div><div class="brand-sub">Capire · ascoltare · creare</div></div><div class="search-wrap"><label for="search">Cerca nella guida</label><input id="search" type="search" placeholder="Intervalli, modi, fase…"><div id="search-status" role="status"></div></div><nav id="nav" aria-label="Capitoli"></nav><div class="sidebar-foot"><div class="progress-caption"><span>Il tuo percorso</span><span id="progress-count"></span></div><progress id="progress" max="27" value="0" aria-label="Capitoli completati"></progress><div class="side-actions"><button id="export">Esporta appunti</button><button id="print">Stampa capitolo</button></div><a class="old-guide" href="../Wavetable-Guida/Wavetable-Live12.html">↗ Guida Wavetable</a></div></aside><main><header class="topbar"><button id="menu" aria-expanded="false" aria-label="Apri o chiudi indice">☰ Indice</button><span class="edition">MUSICA / SUONO / PRODUZIONE</span><div class="master"><label for="master-volume">Volume <output id="master-value">20%</output></label><input id="master-volume" type="range" min="0" max="50" value="20" aria-label="Volume generale percentuale"></div><button id="stop-all">■ Ferma audio · Esc</button></header><div id="audio-status" role="status" aria-live="polite">Audio pronto: avvia un esempio nel laboratorio.</div><div id="page" class="page"></div><footer class="site-footer">STUDIO MANUAL 02 · Esempi originali · Funziona offline · <a href="FONTI.md">Fonti e criteri</a></footer></main><noscript><p>Abilita JavaScript per la guida interattiva. I capitoli Markdown nella cartella capitoli restano leggibili senza JavaScript.</p></noscript><script>const CHAPTERS=${JSON.stringify(chapters).replace(/</g,'\\u003c')};\n${js}</script></body></html>`;
fs.writeFileSync(path.join(base,'Teoria-Musicale.html'),html);console.log(JSON.stringify({chapters:chapters.length,words:chapters.map(c=>c.text).join(' ').split(/\s+/).length,bytes:Buffer.byteLength(html)}));
