const fs=require('node:fs'),path=require('node:path');
const {chromium}=require('C:/Users/tizia/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///'+path.join(__dirname,'Teoria-Musicale.html').replaceAll('\\','/'));const results=[];const chapters=JSON.parse(fs.readFileSync(path.join(__dirname,'indice.json'),'utf8'));
for(const c of chapters){await page.evaluate(id=>{location.hash=id;},c.id);await page.waitForFunction(id=>window.currentLab?.type===id,c.lab);const result=await page.evaluate(async()=>{const {config,params,type}=window.currentLab;const texts=[...document.querySelectorAll('.graph svg')].map(s=>s.outerHTML);let audio=null;if(config.events){const r=await synthesize(config.events(params));let peak=0,energy=0;for(const x of r.channels[0]){if(!Number.isFinite(x))throw Error('Campione non finito');peak=Math.max(peak,Math.abs(x));energy+=x*x;}audio={duration:r.duration,peak,rms:Math.sqrt(energy/r.channels[0].length)};}return {type,audio,svgFinite:texts.every(s=>!s.includes('NaN')&&!s.includes('Infinity')),heading:document.querySelector('h1').textContent,overflow:document.documentElement.scrollWidth>innerWidth};});results.push({id:c.id,...result});if(!result.svgFinite||result.overflow)errors.push(c.id+': layout/grafico');}
// Controlli numerici indipendenti sulle formule e sulla sintesi.
const checks=await page.evaluate(async()=>{const ok=[];function test(name,pass){ok.push({name,pass});}test('A4=440 Hz',hz(69)===440);test('Ottava 2:1',Math.abs(hz(72)/hz(60)-2)<1e-10);test('Scala maggiore, sette gradi',SCALES.major.join(',')==='0,2,4,5,7,9,11');test('Minore armonica, sensibile',SCALES.harmonic[6]===11);test('Diminuito settima',CHORDS.dim7.join(',')==='0,3,6,9');for(let n=3;n<=24;n++)for(let k=0;k<=n;k++){let a=euclidean(k,n,0);if(a.filter(Boolean).length!==k)throw Error('Numero colpi euclideo');if(k){let ids=a.flatMap((v,i)=>v?[i]:[]),g=ids.map((v,i)=>mod(ids[(i+1)%k]-v,n)||n);if(Math.max(...g)-Math.min(...g)>1)throw Error('Distribuzione non uniforme');}}test('Euclidei: tutti k/n fino a 24',true);test('Compressione -10 → -16',createLab('dynamics').transfer(-10,{threshold:-18,ratio:4,makeup:0})===-16);test('Aliasing 6000 @ 8000 → 2000',createLab('alias').alias({freq:6000,fs:8000})===2000);const phase=await synthesize({events:[{f:220,start:0,dur:1,type:'phase',phase:180,detune:0,amp:.5}]});let peak=0;for(const x of phase.channels[0])peak=Math.max(peak,Math.abs(x));test('Cancellazione 180°',peak<1e-10);test('ADSR note-off durante attack',Math.abs(envelope(.75,2,{a:1,d:.5,s:.5,r:1,gate:.5})-.375)<1e-12);test('Spelling G maggiore: F♯ (Fa♯)',spelled(67,11,6)==='F♯ (Fa♯)');test('Spelling F maggiore: B♭ (Si♭)',spelled(65,5,3)==='B♭ (Si♭)');return ok;});
await page.evaluate(()=>location.hash='04-intervalli');await page.waitForSelector('#lab-semi');await page.locator('#lab-semi').fill('7');await page.locator('#lab-semi').dispatchEvent('input');if(!(await page.locator('.graph-caption').textContent()).includes('Quinta giusta'))errors.push('Slider intervalli');await page.locator('.lab-actions .primary').click();await page.waitForFunction(()=>activeSource!==null);await page.keyboard.press('Escape');if(!await page.evaluate(()=>activeSource===null))errors.push('Stop audio');
await page.locator('#notes-text').fill('Verifica salvataggio appunti');await page.reload();if(await page.locator('#notes-text').inputValue()!=='Verifica salvataggio appunti')errors.push('Persistenza appunti');await page.locator('#notes-text').fill('');await page.locator('[data-answer="1"]').click();if(!(await page.locator('.quiz-result').textContent()).includes('Corretto'))errors.push('Quiz');
await page.locator('#search').fill('fondamentale mancante');if(!await page.locator('#nav').textContent().then(t=>t.includes('Psicoacustica')))errors.push('Ricerca');await page.locator('#search').fill('');
await page.evaluate(()=>location.hash='00-percorso');await page.waitForFunction(()=>current===0);await page.screenshot({path:path.join(__dirname,'verifica-desktop.png'),fullPage:false});
await page.evaluate(()=>location.hash='18-inviluppi');await page.waitForSelector('#lab-a');await page.locator('.lab').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,'verifica-laboratorio.png'),fullPage:false});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>location.hash='07-accordi');await page.waitForSelector('#lab-quality');await page.locator('.lab').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,'verifica-mobile.png'),fullPage:false});const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(mobileOverflow)errors.push('Overflow pagina mobile');
await page.locator('#menu').click();if(await page.locator('#menu').getAttribute('aria-expanded')!=='true')errors.push('Menu mobile');
const all={chapters:results,checks,errors,mobileOverflow};fs.writeFileSync(path.join(__dirname,'verifica-risultati.json'),JSON.stringify(all,null,2));console.log(JSON.stringify({chapters:results.length,checks,errors},null,2));await browser.close();if(errors.length||checks.some(c=>!c.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
